import React from 'react'
import SideBar from '../components/SideBar'
import { Col, Container, Row } from 'react-bootstrap'


function DashBoard() {
    return (
        <>
            <Container fluid>
                <Row className="relative flex-wrap-reverse flex-md-row flex-md-wrap">
                    <Col className="bg-slate-100 fixed bottom-0 md:!sticky  z-5 shadow-2xl" sm={12} md={3} lg={2} >
                        <SideBar  />
                    </Col>
                    <Col className='p-5' sm={12} md={9} lg={10}>
                        {/* Details component meera*/}
                        <h1 className='mt-5'>Acitivity Details</h1>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>

                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusa</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>ndae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tenetur, aliquid accusamus. Eum provident nulla facilis consequatur modi magnam quam esse molestiae corrupti eos. Voluptatum, cum! Magnam debitis aliquam recusandae voluptate assumenda earum eum, dicta tempore vero et autem molestiae delectus possimus officia eveniet dolorum perferendis odit facilis iste commodi nemo.</p>

                    </Col>
                </Row>
            </Container>
        </>
    )
}

export default DashBoard